name: Collect

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run
        run: swift run

      - name: Commit
        run: |
          NOW=`date +"%F %H:%M"`
          git config user.name 'Igor'
          git config user.email 'igor.bot@users.noreply.github.com'
          git add -A
          git commit -m "[UMCS] ${NOW}"

      - name: Push
        run: |
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
