name: Collect

on:
  schedule:
     - cron: "*/10 * * * *"
  push:
    branches:
      - master

env:
  DEPLOY_KEY: ${{ secrets.LUSTAPO_DATA_SSH }}

jobs:
  umcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone data repository
        uses: actions/checkout@v2
        with:
          repository: rzeszot/lustapo-data
          path: data

      - name: Prepare
        run: sh .github/scripts/prepare.sh

      - name: Run
        run: swift run

      - name: Save
        run: sh .github/scripts/commit.sh

      - name: Clean
        run: sh .github/scripts/clean.sh
