name: Collect

on:
  push:
    branches:
      - master

jobs:
  umcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare key
        run: |
          echo $LUSTAPO_DATA_SSH > ~/.ssh/lustapo-data.deploy.pem

          cat <<EOT > ~/.ssh/config
          Host lustapo-data
            Hostname github.com
            IdentityFile ~/.ssh/lustapo-data.deploy.pem
          EOT

      - name: Clone data repository
        run: |
          git config user.name 'Igor'
          git config user.email 'igor.bot@users.noreply.github.com'

          git clone git@github.com:rzeszot/lustapo-data.git data

      - name: Run
        run: swift run

      - name: Save
        run: |
          cd data

          git remote set-url origin git@lustapo-data:rzeszot/lustapo-data.git 

          NOW=`date +"%F %H:%M"`
          git add -A
          git commit -m "[UMCS] ${NOW}"

          git push origin master


      - name: Clean
        run: |
          rm ~/.ssh/lustapo-data.deploy.pem
