name: Collect

on:
  push:
    branches:
      - master

jobs:
  umcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare key
        run: |
          sh .github/scripts/prepare.sh "$LUSTAPO_DATA_SSH"

      - name: Clone data repository
        uses: actions/checkout@v2
        with:
          repository: rzeszot/lustapo-data
          path: data

      - name: Run
        run: |
          date > data/test.md
          # swift run

      - name: Save
        run: |
          cd data

          git remote set-url origin git@upstream:rzeszot/lustapo-data.git

          git config user.name 'Igor'
          git config user.email 'igor.bot@users.noreply.github.com'

          NOW=`date +"%F %H:%M"`
          git add -A
          git commit -m "[UMCS] ${NOW}"

          git push origin HEAD:master


      - name: Clean
        run: |
          rm -f ~/.ssh/lustapo_rsa ~/.ssh/config
