name: Collect

on:
  push:
    branches:
      - master

jobs:
  umcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run
        run: swift run

      - name: Prepare key
        run: |
          echo $LUSTAPO_DATA_SSH > ~/.ssh/lustapo-data.deploy.pem

          cat <<EOT > ~/.ssh/config
          Host lustapo-data
            Hostname github.com
            IdentityFile ~/.ssh/lustapo-data.deploy.pem
          EOT

      - name: Clean
        run: |
          rm ~/.ssh/lustapo-data.deploy.pem
